services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: micro-edu-app:latest
    container_name: micro_edu_app
    restart: unless-stopped
    ports:
      - "8086:80"
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=172.26.0.10
      - DB_PORT=3306
      - DB_DATABASE=microedu
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-Moalnyaho123}
      - REDIS_HOST=172.31.0.2
      - REDIS_PASSWORD=${REDIS_PASSWORD:-rahasiamanggie123}
    networks:
      - shared_apps

networks:
  shared_apps:
    external: true
